

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-infra-services
  namespace: argocd
spec:
  project: infra-services
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.9
    chart: external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true